# Generated by Django 5.0.7 on 2024-10-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
