# Generated by Django 5.0.7 on 2024-10-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customer_email_customer_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
