# Generated by Django 5.0.7 on 2024-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_username_customer_user_remove_customer_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
